on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout 'donutboyy/cardvault'
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: npm install
        run: npm install --include=dev

      - name: run eslint
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL}}
        run: npm run lint

      - name: run prettier
        run: npm run format
