name: Migrate Production DB

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout 'donutboyy/cardvault'
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: npm install
        run: npm install --include=dev

      - name: migrate db
        run: |
          npm run db:migrate
